### ISSUE TITLE
Use SpringBoot Demo And Start Application Got Error

### ISSUE THREAD

**Issue by shuaiyinoo** [iohao/ioGameExamples#6]
![WechatIMG24](https://github.com/iohao/ioGame-example/assets/4043623/d7c4c564-7be7-4e8c-a200-815b4088c762)

Use springboot demo and start application got error
Than upgrade my own application form iogame17-> ioGame21 
I got the same issues

please find the problem

great thanks

**Comment by iohao** [comment]
<img width="1480" alt="image" src="https://github.com/iohao/ioGame-example/assets/26356013/4fc8399d-66bb-41f5-ad62-c44ec09b2e76">

Sorry, I can't reproduce this issue.
Please try updating the example and running it again.
